--Selection des tables
SELECT * FROM DESCRIPTEUR;
SELECT Libelle FROM DESCRIPTEUR;
SELECT Description FROM DESCRIPTEUR;

--les object sélectionnés sont à présent des clés étrangéres pointant sur la table DESCRIPTEUR
SELECT DescripteurVedette FROM DESCRIPTEUR_VEDETTE;
SELECT Concept FROM CONCEPT;

SELECT * FROM SYNONYME;
SELECT Descripteur FROM SYNONYME;
SELECT Descripteur2 FROM SYNONYME;

SELECT * FROM ASSOCIATION;
SELECT Descripteur FROM ASSOCIATION;
SELECT DescripteurVedette FROM ASSOCIATION;

SELECT * FROM SPECIALISATION_DESCRIPTEUR;
SELECT DescripteurV FROM SPECIALISATION_DESCRIPTEUR;
SELECT Concept FROM SPECIALISATION_DESCRIPTEUR;

SELECT * FROM SPECIALISATION_CONCEPT;
SELECT ConceptSpecialise FROM SPECIALISATION_CONCEPT;
SELECT ConceptSpecialisant FROM SPECIALISATION_CONCEPT;


--Ajout dans les tables
INSERT INTO DESCRIPTEUR (Descripteur_t('varchar(100)','varchar(500)');
INSERT INTO DESCRIPTEUR_VEDETTE ('varchar(100)');
INSERT INTO SYNONYME ('varchar(100)','varchar(100)');		
INSERT INTO ASSOCIATION ('varchar(100)','varchar(100)');
INSERT INTO SPECIALISATION_DESCRIPTEUR ('varchar(100)','varchar(100)');
INSERT INTO SPECIALISATION_CONCEPT ('varchar(100)','varchar(100)');

--Suppression dans les tables
DELETE FROM DESCRIPTEUR WHERE Libelle = 'varchar(100)';
DELETE FROM DESCRIPTEUR_VEDETTE WHERE DescripteurVedette = 'varchar(100)';
DELETE FROM CONCEPT WHERE Concept = 'varchar(100)';
DELETE FROM SYNONYME WHERE Descripteur = 'varchar(100)' AND Descripteur2 = 'varchar(100)';
DELETE FROM ASSOCIATION WHERE Descripteur = 'varchar(100)' AND DescripteurVedette = 'varchar(100)';
DELETE FROM SPECIALISATION_DESCRIPTEUR WHERE DescripteurV = 'varchar(100)' AND Concept = 'varchar(100)';
DELETE FROM SPECIALISATION_CONCEPT WHERE ConceptSpecialise = 'varchar(100)' AND ConceptSpecialisant = 'varchar(100)';



--Selection par lettre
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'A%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'B%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'C%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'D%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'E%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'F%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'G%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'H%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'I%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'J%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'K%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'L%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'M%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'N%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'O%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'P%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'Q%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'R%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'S%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'T%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'U%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'V%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'W%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'X%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'Y%'
SELECT * FROM DESCRIPTEUR WHERE Libelle LIKE 'Z%'
