--Selection des tables
SELECT * FROM DESCRIPTEUR;
SELECT Libelle FROM DESCRIPTEUR;
SELECT Description FROM DESCRIPTEUR;

--les object sélectionnés sont à présent des clés étrangéres pointant sur la table DESCRIPTEUR
SELECT DescripteurVedette FROM DESCRIPTEUR_VEDETTE;
SELECT Concept FROM CONCEPT;

SELECT * FROM SYNONYME;
SELECT Descripteur FROM SYNONYME;
SELECT Descripteur2 FROM SYNONYME;

SELECT * FROM ASSOCIATION;
SELECT Descripteur FROM ASSOCIATION;
SELECT DescripteurVedette FROM ASSOCIATION;

SELECT * FROM SPECIALISATION_DESCRIPTEUR;
SELECT DescripteurV FROM SPECIALISATION_DESCRIPTEUR;
SELECT Concept FROM SPECIALISATION_DESCRIPTEUR;

SELECT * FROM SPECIALISATION_CONCEPT;
SELECT ConceptSpecialise FROM SPECIALISATION_CONCEPT;
SELECT ConceptSpecialisant FROM SPECIALISATION_CONCEPT;


--Ajout dans les tables
INSERT INTO DESCRIPTEUR (Descripteur_t('varchar(100)','varchar(500)');
INSERT INTO DESCRIPTEUR_VEDETTE ('varchar(100)');
INSERT INTO SYNONYME ('varchar(100)','varchar(100)');		
INSERT INTO ASSOCIATION ('varchar(100)','varchar(100)');
INSERT INTO SPECIALISATION_DESCRIPTEUR ('varchar(100)','varchar(100)');
INSERT INTO SPECIALISATION_CONCEPT ('varchar(100)','varchar(100)');
