-- Liste des spiritueux
INSERT ALL
INTO DESCRIPTEUR VALUES (Descripteur_T('Spiritueux','Une boisson spiritueuse est une boisson alcoolisee obtenue par distillation, suivie eventuellement d''une maceration ou d''une infusion de matieres premieres agricoles. Ces procedes de fabrication distinguent les spiritueux des boissons alcoolisees produites par fermentation (biere, vin, cidre).'))
--
INTO DESCRIPTEUR VALUES (Descripteur_T ('Aquavit', 'L''aquavit est une eau-de-vie de cereale ou de pomme de terre parfumee avec differentes substances aromatiques (cumin, anis, fenouil, cannelle, orange amere, etc.).'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Arak', 'L''Arak est prepare a partir de jus de raisin distille en eau-de-vie auquel on ajoute des graines d''anis.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Armagnac', 'L''armagnac est une eau-de-vie de vin produite dans les departements francais du Gers, des Landes et du Lot-et-Garonne'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Brandy', 'Brandy est un terme de langue anglaise designant une eau-de-vie. Il vient du neerlandais brandewijn signifiant « vin brûle ». Seul, ce terme s''applique plutot a une eau-de-vie de raisin (cognac, armagnac, rakia, etc.). Associe a un nom de fruit il designe un spiritueux provenant de ce fruit, par exemple apricot brandy, cherry brandy.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Calvados', 'Le calvados (appele familierement « calva ») est une eau-de-vie d''origine normande obtenue par distillation de cidre ou de poire.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Cognac', 'Le cognac est une eau-de-vie fine a base de raisin, produite dans une region delimitee centree autour de Cognac. Elle doit respecter des normes et des regles de production bien precises afin de pouvoir obtenir l''appellation « cognac ».'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Floc de Gascogne', 'Le floc de Gascogne est un vin de liqueur, ou mistelle, elabore par melange de « moût » de raisin et d''armagnac jeune.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Gin', 'Le gin est une boisson obtenue en aromatisant de l''alcool rectifie d''origine agricole avec des baies de genevrier.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Grappa', 'La grappa est une eau-de-vie de marc de raisin produite en Italie, dans le canton suisse du Tessin et a Saint-Marin.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Kirsch', 'Le kirsch est une eau-de-vie obtenue par double distillation de jus fermentes de cerises'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Liqueurs', 'Une liqueur est une boisson spiritueuse ayant une teneur en sucre minimale de 100 grammes par litre, obtenue par aromatisation de l''alcool ethylique d''origine agricole ou d''un distillat d''origine agricole.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Mei kwei lu chew', 'Cet alcool est generalement servi en fin de repas dans les restaurants chinois.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Ouzo', 'L''ouzo est une boisson alcoolisee anisee grecque fabriquee a base d''alcool neutre melange a divers aromates (principalement l''anis) puis distille et dilue.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Pastis', 'Le pastis (du provencal pastis : « melange ») est le nom donne a des boissons alcoolisees parfumees a l''anis et a la reglisse.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Pineau des Charentes', 'Le pineau des Charentes est une mistelle, une boisson alcoolisee obtenue par melange de moût et d''eau-de-vie de cognac.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Pontarlier', 'Le pontarlier est une denomination informelle designant un aperitif alcoolise anise confectionne dans la region de Pontarlier en Franche-Comte'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Rakı', 'Le raki est une eau-de-vie consommee en Serbie, en Albanie, en Turquie, au Kosovo, en Armenie et plus generalement dans le Moyen-Orient, aromatisee a l’anis, principalement a base de raisin.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Rhum' , 'Le rhum est une eau-de-vie originaire des Ameriques, produite a partir de la canne a sucre ou de sous-produits de l''industrie sucriere. Il est consomme blanc, vieilli en fût (rhum vieux) ou epice. Il prend alors une coloration ambree plus ou moins foncee. En fonction de la matiere premiere utilisee, il peut être appele agricole ou industriel.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Tequila', 'Le ou la tequila, est une boisson alcoolisee produite au Mexique a partir d''une plante nommee Agave tequilana.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Vins cuits','En France, le vin cuit est un vin artisanal obtenu par concentration du moût de raisin chauffe dans un chaudron et additionne d''epices.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Vodka', 'La vodka est une boisson alcoolisee incolore de 40 degres. L''origine de cette eau-de-vie se situerait en Russie ou en Pologne selon les sources. Il s''agit generalement d''une eau-de-vie de pomme de terre ou de cereales, mais d''autres matieres premieres peuvent être utilisees.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Whisky', 'Le whisky (ou whiskey) est le nom generique d''un ensemble d''eaux-de-vie fabriquees par distillation de cereales maltees ou non maltees.'))
--
-- liste des Liqueurs
--
INTO DESCRIPTEUR VALUES (Descripteur_T ('Absinthe', 'L''absinthe est un ensemble de spiritueux a base de plantes d''absinthe, egalement appele « fee verte » ou encore « bleue ».'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Amaretto', 'L''amaretto est l''une des liqueurs pouvant servir a aromatiser le tiramisù, un dessert italien. Une boisson qui peut s''apprecier autant a l''aperitif (sur glace ou pour beaucoup de cocktails) qu''au digestif, ainsi qu''en shot dans un cadre festif.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Amaro', 'Amaro (en francais: amer) est un terme italien qui designe une variete de liqueur a base de plantes.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Anisette', 'une liqueur a base d''anis vert et de diverses autres plantes, dont le degre d''alcool varie de 20 a 25 ° d''alcool.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Benedictine', 'La Benedictine est une boisson alcoolisee digestive fabriquee a Fecamp en Normandie.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Amers', 'L''amer (appele aussi amere ou bitter) est une liqueur aperitive fabriquee a partir de l''infusion de plantes ameres. Certains amers entrent dans la composition de differents cocktails.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Chartreuse', 'La chartreuse est une liqueur fabriquee par les moines chartreux dans les caves de Voiron en Isere, en bordure du Massif de la Chartreuse.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Cointreau', 'Le cointreau est une liqueur a base d''ecorces d''oranges douces et ameres (Citrus bigaradia), creee en 1875 a Angers, proche du triple sec. C''est aussi une marque appartenant a l''entreprise Remy Cointreau.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Curacao', 'Le curacao est une liqueur d''orange titrant entre 20 ° et 40 ° utilisee pour confectionner de nombreux cocktails.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Drambuie', 'Drambuie (prononcez drambouie) est une marque de liqueur fabriquee a partir de Scotch.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Genepi', 'Ce nom designe la liqueur obtenue par la maceration des plantes Artemisia.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Gold Strike', 'Le Gold Strike est une liqueur aromatisee a la cannelle produite par Bols.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Grand Marnier', 'Le grand marnier est une liqueur a base de Cognac et d''oranges, du même type que le curacao.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Guignolet', 'Le guignolet est une liqueur originaire d''Anjou a base de cerises aigres et noires. Il doit son nom a la guigne, l''une des especes de cerises qu''il utilise dans sa preparation.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Izarra', 'L''Izarra, qui signifie l''etoile en basque, est une marque de liqueur creee en 1906 a Hendaye. Izarra est une liqueur realisee a base de plantes et d''epices, de brou de noix, de pruneaux et d''Armagnac.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Kahlua', 'Le Kahlúa est une liqueur a base de cafe originaire du Mexique. C''est la liqueur aromatisee au cafe la plus vendue au monde'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Kummel', 'Le kummel est une boisson alcoolisee allemande ou neerlandaise titrant environ 35-40°, aromatisee principalement avec du carvi ainsi qu''avec d''autres epices et herbes.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Licor 43', 'Licor 43, ou Cuarenta y Tres (43 en espagnol) est une liqueur espagnole tres ancienne, composee de 43 ingredients, dont de la vanille. De couleur jaune et de texture epaisse, Cuarenta y Tres titre 31° d''alcool.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Liqueur de myrte', 'La liqueur de myrte, ou plus simplement myrte, est une liqueur, tres populaire en Corse et en Sardaigne, obtenue par maceration alcoolique de baies de myrte ou d''un melange de baies et de feuilles. Dans l''acception courante du terme, la liqueur de myrte est le resultat de la maceration de baies pigmentees mûres.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Myrte', 'Voir definition Liqueur de myrte'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Noyau de Poissy', 'Le Vrai Noyau de Poissy est une liqueur a base d’amandons de noyaux d’abricots, maceres ou distilles dans un alcool surfin, en presence, selon les recettes, de fine eau de vie de vin, enrichies de plantes et subtilement aromatisees.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Liqueur de sapin', 'La liqueur de sapin est une boisson alcoolisee a base de bourgeons de sapins, obtenue par distillation et produite a Pontarlier dans le Doubs en region Franche-Comte, France.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Liqueur de Poejo', 'Le Poejo est une liqueur typique Portugaise. Elle est a base de menthe pouliot (Mentha pulegium). C''est une des plus anciennes liqueurs du Portugal, au même titre que la liqueur de Ginja d''Óbidos, Alcobaca et Caldas da Rainha. La liqueur de poejo apparait sous trois couleurs differentes : verte, jaune ou transparente. '))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Rhubarbe Zucca', 'Le Rabarbaro Zucca est un amer italien a base de rhubarbe (Rabarbaro en italien). En revanche, il ne contient pas de courge (zucca en italien), mais tire son nom commercial de son createur, Ettore Zucca, qui l''inventa en 1845 a Milan'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Sambuca', 'La sambuca est le nom donne a une liqueur italienne douce et forte a base d''anis etoile, creee a Civitavecchia, dans la province de Rome, en 1851.'))
INTO Descripteur VALUES (Descripteur_T ('Thibarine', 'La thibarine est un alcool de dattes generalement aromatise avec des plantes. Elle titre en moyenne 40°.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Triple sec', 'Un triple sec est une liqueur d''ecorces d''orange utilisee dans de tres nombreux cocktails et recettes. Elle resulte d''une triple distillations d''ecorces d''oranges douces et ameres.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Vermouth', 'Le vermouth est un aperitif a base de vin blanc, obtenu par addition de sucre ou de mistelle (melange de moût de raisin et d''alcool), d''alcool neutre et aromatise par une infusion de nombreuses plantes aromatiques. Il titre entre 16° et 18° d''alcool. Le vermouth rouge doit sa couleur a l''adjonction de caramel.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Verveine', 'La liqueur de verveine est une production artisanale, familiale surtout, que l''on trouve dans les Alpes et en Haute-Loire (Verveine du Velay), et probablement ailleurs, fabriquee a partir de la verveine citronnelle.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Vespetro', 'Le Vespetro est une liqueur italienne d''origine savoyarde ancienne aux vertus carminatives reconnues'))
--
-- liste des Amers
--
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Abbot''s Aged Bitters', 'Est prepare a l''origine a Baltimore (Maryland - etats-Unis) des 1865. Le constituant principal est l''orange amere, et plus exactement, la peau sechee de la variete "orange de Seville".'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Amaro Lucano', 'L''Amaro Lucano est un amer italien.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Angostura' , 'L''angostura est un assaisonnement de couleur brune de 44 ° elabore a base de rhum, de gentiane, d''ecorces d''orange, de substances ameres et d''aromates.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Campari', 'Campari est une entreprise italienne produisant un amaro de couleur rouge vif, parfume avec de l''ecorce d''orange et diverses herbes aromatiques.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Fernet Branca', 'Fernet-Branca est la denomination commerciale d''un amer italien, inventee en 1836 par Bernardino Branca.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('China Martini', 'Le China Martini est un amer italien a base de quinquina jaune appartenant au groupe Martini et Rossi.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Cynar','Le Cynar est une marque d''amer italien obtenu a partir d''un melange de feuilles d''artichauts et de treize herbes et plantes aromatiques infusees dans un alcool. Il tire son nom du genre de l''artichaut, Cynara.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Jägermeister', 'Le Jägermeister (maitre chasseur en allemand) est une liqueur a base de plantes medicinales titrant 35°. Les 56 herbes qui entrent dans sa composition sont tenues secretes.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Liqueur de gentiane', 'La liqueur de gentiane est une boisson aperitive amere et alcoolisee fabriquee par maceration et distillation de racines de gentiane jaune d''Auvergne (gentiana lutea) qui lui conferent son amertume bien specifique.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Orange bitters', 'L''Orange bitters est un amer (bitter) d''origine anglaise. Il est tres utilise et tres prise au Royaume-uni, comme composant de divers cocktails. Son goût particulier provient d''ecorces aigrelettes de la region de Seville.'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Picon', 'Le Picon est un amer, de couleur caramel qui accompagne traditionnellement la biere dans l''est et le nord de la France, en Belgique et au Luxembourg. Il est elabore a base de zestes d''oranges frais et seches puis maceres dans une solution d''alcool puis mis en distillation. Le Picon necessite egalement des racines de gentiane et du quinquina, tous deux maceres egalement. Du sirop de sucre et du caramel sont rajoutes par la suite.'))
INTO Descripteur VALUES  (Descripteur_T ('Suze', 'La Suze est une marque commerciale francaise qui designe une liqueur de gentiane aperitive amere de couleur doree a base de gentianes jaunes'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Unicum', 'L''Unicum est une liqueur hongroise amere a base de plantes medicinales, que l''on consomme en tant qu''aperitif ou digestif.'))
--
-- Liste des Gin
--
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Genever' , 'Gin hollandais'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('London Dry Gin', 'Gin anglais'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Old tom Gin', 'Gin legerement sucre'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Yellow gin', 'gin vieilli en fûts de chêne ayant contenue du Xeres'))
INTO DESCRIPTEUR VALUES  (Descripteur_T ('Cork Gin', 'gin irlandais'))
--
-- Liste des ingredients et fruits ..
--
INTO DESCRIPTEUR VALUES (Descripteur_T ('Canelle', 'La canelle c''est bon'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Artichaut', 'L''artichaut est une plante dicotyledone de la famille des Asteracees (ou Composees) appartenant au genre Cynara.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Ecorces d''orange', 'Utilisee pour quelques boissons.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Orange', 'L''orange est un fruit appartenant a la famille des agrumes.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Anis', 'L''anis est le nom de plusieurs vegetaux aromatiques'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Baies', 'Une baie est un type de fruit charnu'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Plantes', 'Les plantes aromatiques sont un ensemble de plantes utilisees en cuisine et en phytotherapie pour les aromes qu''elles degagent, et leurs huiles essentielles que l''on peut extraire.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Herbes', 'Les herbes aromatiques sont un ensemble d''herbes utilisees en cuisine et en phytotherapie pour les aromes qu''elles degagent.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Aromates', 'Herbes et Epices'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Epices', 'Les epices sont des produits agricoles issus de cultures ou de cueillettes dans la nature. Les epices peuvent être issues d’ecorces, de fleurs, de feuilles, de fruits, de bulbes ou de graines.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Cerise', 'La cerise est le fruit comestible du cerisier.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Cafe', 'Le cafe est une boisson obtenue a partir des graines du cafeier, un arbuste du genre Coffea.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Vanille', 'La vanille est une epice constituee par le fruit de certaines orchidees lianescentes tropicales d''origine mesoamericaine'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Menthe', 'La menthe est l''une des plantes medicinales les plus celebres. Elle aurait des vertus digestives, spasmolytiques, carminatives, antiseptiques, toniques et stimulantes. Elle participerait a l’equilibre digestif et ameliorerait le tonus general.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Datte', 'La datte est le fruit comestible du palmier dattier.'))
INTO DESCRIPTEUR VALUES (Descripteur_T ('Rhubarbe', 'La rhubarbe (genre Rheum) est le nom commun d''une trentaine d''especes de plantes herbacees vivaces de la famille des Polygonacees.'))
--INTO DESCRIPTEUR VALUES (Descripteur_T ('Eau de vie', ''))
--
SELECT * FROM dual;
-- FIN DES DESCRIPTEURS


--DESCRIPTEUR VEDETTE
INSERT ALL
INTO DESCRIPTEUR_VEDETTE VALUES ('Spiritueux')
-- Spiritueux
--
INTO DESCRIPTEUR_VEDETTE VALUES ('Aquavit')
INTO DESCRIPTEUR_VEDETTE VALUES ('Arak')
INTO DESCRIPTEUR_VEDETTE VALUES ('Armagnac')
INTO DESCRIPTEUR_VEDETTE VALUES ('Brandy')
INTO DESCRIPTEUR_VEDETTE VALUES ('Calvados')
INTO DESCRIPTEUR_VEDETTE VALUES ('Cognac')
INTO DESCRIPTEUR_VEDETTE VALUES ('Floc de Gascogne')
INTO DESCRIPTEUR_VEDETTE VALUES ('Gin')
INTO DESCRIPTEUR_VEDETTE VALUES ('Grappa')
INTO DESCRIPTEUR_VEDETTE VALUES ('Kirsch')
INTO DESCRIPTEUR_VEDETTE VALUES ('Liqueurs')
INTO DESCRIPTEUR_VEDETTE VALUES ('Mei kwei lu chew')
INTO DESCRIPTEUR_VEDETTE VALUES ('Ouzo')
INTO DESCRIPTEUR_VEDETTE VALUES ('Pastis')
INTO DESCRIPTEUR_VEDETTE VALUES ('Pineau des Charentes')
INTO DESCRIPTEUR_VEDETTE VALUES ('Pontarlier')
INTO DESCRIPTEUR_VEDETTE VALUES ('Rakı')
INTO DESCRIPTEUR_VEDETTE VALUES ('Rhum')
INTO DESCRIPTEUR_VEDETTE VALUES ('Tequila')
INTO DESCRIPTEUR_VEDETTE VALUES ('Vins cuits')
INTO DESCRIPTEUR_VEDETTE VALUES ('Vodka')
INTO DESCRIPTEUR_VEDETTE VALUES ('Whisky') 
-- Descripteur vedette - Liqueurs
--
INTO DESCRIPTEUR_VEDETTE VALUES ('Absinthe')
INTO DESCRIPTEUR_VEDETTE VALUES ('Amaretto')
INTO DESCRIPTEUR_VEDETTE VALUES ('Amaro')
INTO DESCRIPTEUR_VEDETTE VALUES ('Amers')
INTO DESCRIPTEUR_VEDETTE VALUES ('Anisette')
INTO DESCRIPTEUR_VEDETTE VALUES ('Benedictine')
INTO DESCRIPTEUR_VEDETTE VALUES ('Chartreuse')
INTO DESCRIPTEUR_VEDETTE VALUES ('Cointreau')
INTO DESCRIPTEUR_VEDETTE VALUES ('Curacao')
INTO DESCRIPTEUR_VEDETTE VALUES ('Drambuie')
INTO DESCRIPTEUR_VEDETTE VALUES ('Genepi')
INTO DESCRIPTEUR_VEDETTE VALUES ('Gold Strike')
INTO DESCRIPTEUR_VEDETTE VALUES ('Grand Marnier')
INTO DESCRIPTEUR_VEDETTE VALUES ('Guignolet')
INTO DESCRIPTEUR_VEDETTE VALUES ('Izarra')
INTO DESCRIPTEUR_VEDETTE VALUES ('Kahlua')
INTO DESCRIPTEUR_VEDETTE VALUES ('Kummel')
INTO DESCRIPTEUR_VEDETTE VALUES ('Licor 43')
INTO DESCRIPTEUR_VEDETTE VALUES ('Liqueur de myrte')
INTO DESCRIPTEUR_VEDETTE VALUES ('Myrte')
INTO DESCRIPTEUR_VEDETTE VALUES ('Noyau de Poissy')
INTO DESCRIPTEUR_VEDETTE VALUES ('Liqueur de sapin')
INTO DESCRIPTEUR_VEDETTE VALUES ('Liqueur de Poejo')
INTO DESCRIPTEUR_VEDETTE VALUES ('Rhubarbe Zucca')
INTO DESCRIPTEUR_VEDETTE VALUES ('Sambuca')
INTO DESCRIPTEUR_VEDETTE VALUES ('Thibarine')
INTO DESCRIPTEUR_VEDETTE VALUES ('Triple sec')
INTO DESCRIPTEUR_VEDETTE VALUES ('Vermouth')
INTO DESCRIPTEUR_VEDETTE VALUES ('Verveine')
INTO DESCRIPTEUR_VEDETTE VALUES ('Vespetro')
-- Descripteur vedette - Amers
--
INTO DESCRIPTEUR_VEDETTE VALUES ('Abbot''s Aged Bitters')
INTO DESCRIPTEUR_VEDETTE VALUES ('Amaro Lucano')
INTO DESCRIPTEUR_VEDETTE VALUES ('Angostura')
INTO DESCRIPTEUR_VEDETTE VALUES ('Campari')
INTO DESCRIPTEUR_VEDETTE VALUES ('Fernet Branca')
INTO DESCRIPTEUR_VEDETTE VALUES ('China Martini')
INTO DESCRIPTEUR_VEDETTE VALUES ('Cynar')
INTO DESCRIPTEUR_VEDETTE VALUES ('Jägermeister')
INTO DESCRIPTEUR_VEDETTE VALUES ('Liqueur de gentiane')
INTO DESCRIPTEUR_VEDETTE VALUES ('Orange bitters')
INTO DESCRIPTEUR_VEDETTE VALUES ('Picon')
INTO DESCRIPTEUR_VEDETTE VALUES ('Suze')
INTO DESCRIPTEUR_VEDETTE VALUES ('Unicum')
-- Descripteur vedette - Les Gin
INTO DESCRIPTEUR_VEDETTE VALUES ('Genever')
INTO DESCRIPTEUR_VEDETTE VALUES ('London Dry Gin')
INTO DESCRIPTEUR_VEDETTE VALUES ('Old tom Gin')
INTO DESCRIPTEUR_VEDETTE VALUES ('Yellow gin')
INTO DESCRIPTEUR_VEDETTE VALUES ('Cork Gin')
--
--
SELECT * FROM dual;
-- FIN DES DESCRIPTEURS VEDETTE

--CONCEPT
INSERT ALL
--
INTO CONCEPT VALUES ('Spiritueux')
--
-- Spiritueux
INTO CONCEPT VALUES ('Aquavit')
INTO CONCEPT VALUES ('Arak')
INTO CONCEPT VALUES ('Armagnac')
INTO CONCEPT VALUES ('Brandy')
INTO CONCEPT VALUES ('Calvados')
INTO CONCEPT VALUES ('Cognac')
INTO CONCEPT VALUES ('Floc de Gascogne')
INTO CONCEPT VALUES ('Gin')
INTO CONCEPT VALUES ('Grappa')
INTO CONCEPT VALUES ('Kirsch')
INTO CONCEPT VALUES ('Liqueurs')
INTO CONCEPT VALUES ('Mei kwei lu chew')
INTO CONCEPT VALUES ('Ouzo')
INTO CONCEPT VALUES ('Pastis')
INTO CONCEPT VALUES ('Pineau des Charentes')
INTO CONCEPT VALUES ('Pontarlier')
INTO CONCEPT VALUES ('Rakı')
INTO CONCEPT VALUES ('Rhum')
INTO CONCEPT VALUES ('Tequila')
INTO CONCEPT VALUES ('Vins cuits')
INTO CONCEPT VALUES ('Vodka')
INTO CONCEPT VALUES ('Whisky') 
--
-- CONCEPT - Liqueurs
INTO CONCEPT VALUES ('Absinthe')
INTO CONCEPT VALUES ('Amaretto')
INTO CONCEPT VALUES ('Amaro')
INTO CONCEPT VALUES ('Amers')
INTO CONCEPT VALUES ('Anisette')
INTO CONCEPT VALUES ('Benedictine')
INTO CONCEPT VALUES ('Chartreuse')
INTO CONCEPT VALUES ('Cointreau')
INTO CONCEPT VALUES ('Curacao')
INTO CONCEPT VALUES ('Drambuie')
INTO CONCEPT VALUES ('Genepi')
INTO CONCEPT VALUES ('Gold Strike')
INTO CONCEPT VALUES ('Grand Marnier')
INTO CONCEPT VALUES ('Guignolet')
INTO CONCEPT VALUES ('Izarra')
INTO CONCEPT VALUES ('Kahlua')
INTO CONCEPT VALUES ('Kummel')
INTO CONCEPT VALUES ('Licor 43')
INTO CONCEPT VALUES ('Liqueur de myrte')
INTO CONCEPT VALUES ('Myrte')
INTO CONCEPT VALUES ('Noyau de Poissy')
INTO CONCEPT VALUES ('Liqueur de sapin')
INTO CONCEPT VALUES ('Liqueur de Poejo')
INTO CONCEPT VALUES ('Rhubarbe Zucca')
INTO CONCEPT VALUES ('Sambuca')
INTO CONCEPT VALUES ('Thibarine')
INTO CONCEPT VALUES ('Triple sec')
INTO CONCEPT VALUES ('Vermouth')
INTO CONCEPT VALUES ('Verveine')
INTO CONCEPT VALUES ('Vespetro')
--
-- CONCEPT - Amers
--
INTO CONCEPT VALUES ('Abbot''s Aged Bitters')
INTO CONCEPT VALUES ('Amaro Lucano')
INTO CONCEPT VALUES ('Angostura')
INTO CONCEPT VALUES ('Campari')
INTO CONCEPT VALUES ('Fernet Branca')
INTO CONCEPT VALUES ('China Martini')
INTO CONCEPT VALUES ('Cynar')
INTO CONCEPT VALUES ('Jägermeister')
INTO CONCEPT VALUES ('Liqueur de gentiane')
INTO CONCEPT VALUES ('Orange bitters')
INTO CONCEPT VALUES ('Picon')
INTO CONCEPT VALUES ('Suze')
INTO CONCEPT VALUES ('Unicum')
--
-- CONCEPT - Les Gin
--
INTO CONCEPT VALUES ('Genever')
INTO CONCEPT VALUES ('London Dry Gin')
INTO CONCEPT VALUES ('Old tom Gin')
INTO CONCEPT VALUES ('Yellow gin')
INTO CONCEPT VALUES ('Cork Gin')
--
SELECT * FROM dual;
-- FIN DES CONCEPTS

-- SPECIALISATION DescripteurVedette Concept
-- SPECIALISATION_DESCRIPTEUR OU SPECIALISATION_CONCEPT ? MOTHERFUCKERBITCH (please) !
INSERT ALL
	-- Les Spiritueux
	INTO SPECIALISATION_CONCEPT VALUES ('Aquavit' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Arak' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Armagnac' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Brandy' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Calvados' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Cognac' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Floc de Gascogne' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Gin' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Grappa' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Kirsch' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Liqueurs' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Mei kwei lu chew' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Ouzo' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Pastis' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Pineau des Charentes' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Pontarlier' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Rakı' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Rhum' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Tequila' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Vins cuits' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Vodka' , 'Spiritueux')
	INTO SPECIALISATION_CONCEPT VALUES ('Whisky' , 'Spiritueux')
	-- Les Liqueurs
	INTO SPECIALISATION_CONCEPT VALUES ('Absinthe' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Amaretto' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Amaro' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Anisette' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Amers' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Benedictine' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Chartreuse' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Cointreau' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Curacao' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Drambuie' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Genepi' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Gold Strike' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Grand Marnier' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Guignolet' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Izarra' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Kahlua' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Kummel' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Licor 43' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Liqueur de myrte' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Myrte' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Noyau de Poissy' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Liqueur de sapin' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Liqueur de Poejo' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Rhubarbe Zucca' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Sambuca' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Thibarine' , 'Liqueurs')
	INTO SPECIALISATION_CONCEPT VALUES ('Triple sec' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Vermouth' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Verveine' , 'Liqueurs' )
	INTO SPECIALISATION_CONCEPT VALUES ('Vespetro' , 'Liqueurs' )
	-- Les Amers
	INTO SPECIALISATION_CONCEPT VALUES ('Abbot''s Aged Bitters' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Amaro Lucano' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Angostura' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Campari' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Fernet Branca' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('China Martini' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Cynar' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Jägermeister' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Liqueur de gentiane' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Orange bitters' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Picon' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Suze' , 'Amers')
	INTO SPECIALISATION_CONCEPT VALUES ('Unicum' , 'Amers')
	-- Les Gin
	INTO SPECIALISATION_CONCEPT VALUES ('Genever' , 'Gin')
	INTO SPECIALISATION_CONCEPT VALUES ('London Dry Gin' , 'Gin')
	INTO SPECIALISATION_CONCEPT VALUES ('Old tom Gin' , 'Gin')
	INTO SPECIALISATION_CONCEPT VALUES ('Yellow gin' , 'Gin')
	INTO SPECIALISATION_CONCEPT VALUES ('Cork Gin' , 'Gin')
SELECT * FROM dual;


--ASSOCIATION Descripteur-DescripteurVedette
INSERT ALL 
	-- Les Spiritueux
	INTO ASSOCIATION VALUES	('Eau de vie', 'Whisky')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Vodka')
	INTO ASSOCIATION VALUES	('Plantes', 'Tequila')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Rhum')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Rakı')
	INTO ASSOCIATION VALUES	('Anis', 'Pontarlier')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Pineau des Charentes')
	INTO ASSOCIATION VALUES	('Anis', 'Pastis')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Kirsch')
	INTO ASSOCIATION VALUES	('Cerise', 'Kirsch')
	INTO ASSOCIATION VALUES	('Baies', 'Gin')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Cognac')
	INTO ASSOCIATION VALUES ('Raisin', 'Cognac')
	INTO ASSOCIATION VALUES ('Raisin', 'Floc de Gascogne')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Calvados')
	--INTO ASSOCIATION VALUES	('Cidre', 'Calvados')
	--INTO ASSOCIATION VALUES	('Poire', 'Calvados')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Brandy')
	INTO ASSOCIATION VALUES ('Raisin', 'Arak')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Aquavit')
	INTO ASSOCIATION VALUES	('Anis', 'Aquavit')
	INTO ASSOCIATION VALUES	('Orange', 'Aquavit')
	INTO ASSOCIATION VALUES	('Canelle', 'Aquavit')
	INTO ASSOCIATION VALUES	('Epices', 'Vins cuits')
	--INTO ASSOCIATION VALUES	('Biere', 'Spiritueux')
	--INTO ASSOCIATION VALUES	('Vin', 'Spiritueux')
	--INTO ASSOCIATION VALUES	('Cidre', 'Spiritueux')
	-- Les Liqueurs	
	INTO ASSOCIATION VALUES	('Datte', 'Thibarine')
	--INTO ASSOCIATION VALUES ('Vin blanc', 'Vermouth')
	INTO ASSOCIATION VALUES	('Plantes', 'Vermouth')
	INTO ASSOCIATION VALUES	('Ecorces d''orange', 'Triple sec')
	INTO ASSOCIATION VALUES	('Anis', 'Sambuca')
	INTO ASSOCIATION VALUES	('Rhubarbe', 'Rhubarbe Zucca')
	INTO ASSOCIATION VALUES	('Menthe', 'Liqueur de Poejo')
	INTO ASSOCIATION VALUES	('Baies', 'Liqueur de myrte')
	INTO ASSOCIATION VALUES	('Vanille', 'Licor 43')
	INTO ASSOCIATION VALUES	('Epices', 'Kummel')
	INTO ASSOCIATION VALUES	('Herbes', 'Kummel')
	INTO ASSOCIATION VALUES	('Cafe', 'Kahlua')
	INTO ASSOCIATION VALUES	('Orange', 'Grand Marnier')
	INTO ASSOCIATION VALUES	('Cognac', 'Grand Marnier')
	INTO ASSOCIATION VALUES	('Plantes', 'Genepi')
	INTO ASSOCIATION VALUES	('Orange', 'Curacao')
	INTO ASSOCIATION VALUES	('Ecorces d''orange', 'Cointreau')
	INTO ASSOCIATION VALUES	('Plantes', 'Amers') 
	INTO ASSOCIATION VALUES	('Anis', 'Anisette')
	INTO ASSOCIATION VALUES	('Plantes', 'Amaro')
	INTO ASSOCIATION VALUES	('Plantes', 'Absinthe')
	INTO ASSOCIATION VALUES	('Canelle', 'Gold Strike')
	-- Les Amers
	INTO ASSOCIATION VALUES	('Orange', 'Abbot''s Aged Bitters')
	INTO ASSOCIATION VALUES	('Eau de vie', 'Cynar')
	INTO ASSOCIATION VALUES	('Artichaut', 'Cynar')
	INTO ASSOCIATION VALUES	('Orange', 'Orange bitters')	
	INTO ASSOCIATION VALUES	('Ecorces d''orange', 'Campari')
	INTO ASSOCIATION VALUES	('Herbes', 'Campari')
	INTO ASSOCIATION VALUES	('Ecorces d''orange', 'Angostura')
	INTO ASSOCIATION VALUES	('Rhum', 'Angostura')
	INTO ASSOCIATION VALUES	('Herbes', 'Angostura')
	INTO ASSOCIATION VALUES	('Aromates', 'Angostura')
SELECT * FROM dual;

-- SYNONYME Descripteur-DescripteurVedette
INSERT ALL
	-- Les Spiritueux
	-- Les Liqueurs
	INTO SYNONYME VALUES ('Liqueur de myrte' , 'Myrte' )
	INTO SYNONYME VALUES ('Suze' , 'Liqueur de gentiane' )
	-- Les Amers
	-- Les Gin
SELECT * FROM dual;
