SELECT Libelle FROM DESCRIPTEUR;

SELECT Libelle FROM DESCRIPTEUR_VEDETTE;

SELECT Libelle FROM CONCEPT;

SELECT * FROM SYNONYME;

SELECT * FROM ASSOCIATION;

SELECT * FROM SPECIALISATION_DESCRIPTEUR;

SELECT * FROM SPECIALISATION_CONCEPT;
